//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbusDataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingTrailerInfo
    {
        public int ID { get; set; }
        public int TrailerTypeID { get; set; }
        public int QuotationID { get; set; }
        public Nullable<int> TrailerID { get; set; }
        public Nullable<int> BookingVehicleID { get; set; }
        public bool IsTrailerAssigned { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual BookingQuoteInfo BookingQuoteInfo { get; set; }
        public virtual TrailerType TrailerType { get; set; }
    }
}
