//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbusDataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingReporting
    {
        public string OrganiserName { get; set; }
        public string QuotationNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public string CompanyName { get; set; }
        public System.DateTime QuotationDate { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public double QuotationValue { get; set; }
        public string BusType { get; set; }
        public string FleetNumber { get; set; }
        public string DriverName { get; set; }
        public string DriverNumber { get; set; }
        public System.DateTime PickUpDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public string IsBookingDone { get; set; }
        public double Distance { get; set; }
        public Nullable<double> OperatedKms { get; set; }
        public Nullable<double> DifferenceKms { get; set; }
        public Nullable<bool> IsJobCompleted { get; set; }
        public double InvoiceTotal { get; set; }
        public double PaymentDifference { get; set; }
    }
}
