//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbusDataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingVehicleInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingVehicleInfo()
        {
            this.DispatcherVehicleChecklists = new HashSet<DispatcherVehicleChecklist>();
            this.DispatcherVehicleCustomerSurveys = new HashSet<DispatcherVehicleCustomerSurvey>();
        }
    
        public int ID { get; set; }
        public int QuotationID { get; set; }
        public int BusTypeID { get; set; }
        public Nullable<int> BusID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public string TimeOfLeavingDepot { get; set; }
        public string SpeedoReadingBefore { get; set; }
        public string TimeOfReturnDepot { get; set; }
        public string SpeedoReadingReturn { get; set; }
        public bool IsVehicleAssigned { get; set; }
        public bool IsJobCompleted { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual BookingQuoteinfo BookingQuoteinfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DispatcherVehicleChecklist> DispatcherVehicleChecklists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DispatcherVehicleCustomerSurvey> DispatcherVehicleCustomerSurveys { get; set; }
        public virtual BusType BusType { get; set; }
    }
}
