//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbusDataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatcherBookingInfo
    {
        public int ID { get; set; }
        public string AlternateID { get; set; }
        public string CompanyName { get; set; }
        public string OrganiserName { get; set; }
        public string CellNumber { get; set; }
        public string PickUpTime { get; set; }
        public System.DateTime PickUpDate { get; set; }
        public string ReturnTime { get; set; }
        public string FromLocation { get; set; }
        public string ToLocation { get; set; }
        public Nullable<int> NumberOfTrailers { get; set; }
        public Nullable<int> NumberOfBusses { get; set; }
        public string BusType { get; set; }
        public string FleetNumber { get; set; }
        public string DriverName { get; set; }
        public bool IsVehicleAssigned { get; set; }
        public bool IsTrailerAssigned { get; set; }
        public bool IsJobCompleted { get; set; }
        public int BookingID { get; set; }
        public int BookingVehicleID { get; set; }
    }
}
