//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EbusDataProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispatcherVehicleCustomerSurvey
    {
        public int ID { get; set; }
        public int QuotationID { get; set; }
        public int BookingVehicleID { get; set; }
        public bool WasDrivingOnTime { get; set; }
        public bool WasDriverProperlyAttired { get; set; }
        public bool DidHeKnowTheRoute { get; set; }
        public bool DidHeAdhereToTrafficRules { get; set; }
        public bool AreMapsAvailable { get; set; }
        public string CustomerComments { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual BookingQuoteinfo BookingQuoteinfo { get; set; }
        public virtual BookingVehicleInfo BookingVehicleInfo { get; set; }
    }
}
